name: infinicard_v1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  xml:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Garamond
      fonts:
        - asset: fonts/EBGaramond-Regular.ttf
        - asset: fonts/EBGaramond-Bold.ttf
          weight: 700
        - asset: fonts/EBGaramond-Italic.ttf
          style: italic
        - asset: fonts/EBGaramond-BoldItalic.ttf
          style: italic
          weight: 700
